[package]
name = "incident_channel"
version = "0.1.0"
authors = ["Scott Hardy <scott.the.hardy@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
frank_jwt = "3.0.2"
reqwest = "0.9.2"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
serde_json = "1.0"
slack_api = "0.21.0"
